import { Menu, Search, Bell, Sun, Moon, ChevronDown, LogOut, UserRound, Settings } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { useTheme } from "../../context/theme";
import { useAuth } from "../../context/AuthContext";

export default function Topbar({ onMenuClick }) {
  const { darkMode, toggleTheme } = useTheme(); const { user, logout } = useAuth(); const navigate = useNavigate();
  const signOut = async () => { await logout(); navigate("/login"); };
  return <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200 bg-white/95 px-4 backdrop-blur md:px-6 dark:border-slate-800 dark:bg-slate-950/95"><div className="flex items-center gap-3"><button onClick={onMenuClick} className="rounded-lg p-2 text-slate-600 hover:bg-slate-100 lg:hidden dark:text-slate-300 dark:hover:bg-slate-800"><Menu size={21} /></button><div className="relative hidden md:block"><Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input type="search" placeholder="Search projects, tasks, issues..." className="w-72 rounded-xl border border-slate-200 bg-slate-50 py-2 pl-10 pr-4 text-sm outline-none transition focus:border-blue-500 focus:bg-white dark:border-slate-700 dark:bg-slate-900 dark:text-white" /></div></div><div className="flex items-center gap-2"><button onClick={toggleTheme} className="rounded-xl p-2.5 text-slate-500 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800" title="Toggle theme">{darkMode ? <Sun size={19} /> : <Moon size={19} />}</button><Link to="/notifications" className="relative rounded-xl p-2.5 text-slate-500 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800"><Bell size={19} /><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-red-500" /></Link><div className="group relative ml-1"><button className="flex items-center gap-2 rounded-xl p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-600 text-sm font-semibold text-white">{user?.name?.[0]?.toUpperCase() || "D"}</div><div className="hidden text-left md:block"><p className="text-sm font-semibold text-slate-800 dark:text-white">{user?.name || "DevFlow user"}</p><p className="text-xs capitalize text-slate-400">{user?.role || "member"}</p></div><ChevronDown size={16} className="hidden text-slate-400 md:block" /></button><div className="invisible absolute right-0 top-full z-50 mt-2 w-44 rounded-xl border border-slate-700 bg-slate-900 p-1 opacity-0 shadow-xl transition group-hover:visible group-hover:opacity-100"><Link to="/profile" className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-slate-300 hover:bg-slate-800"><UserRound size={15} />Profile</Link><Link to="/settings" className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-slate-300 hover:bg-slate-800"><Settings size={15} />Settings</Link><button onClick={signOut} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm text-rose-300 hover:bg-slate-800"><LogOut size={15} />Logout</button></div></div></div></header>;
}
