import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import api from "../../services/api";

export default function ResourcePage({ title, subtitle, endpoint, fields = [], defaultStatus }) {
  const [items, setItems] = useState([]); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { try { const { data } = await api.get(endpoint); setItems(data.data); } catch (err) { setError(err.response?.data?.message || "Unable to load data."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [endpoint]);
  const create = async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const { data } = await api.post(endpoint, { ...values, status: defaultStatus }); setItems((current) => [data.data, ...current]); setOpen(false); } catch (err) { setError(err.response?.data?.message || "Unable to create item."); } };
  const remove = async (id) => { await api.delete(`${endpoint}/${id}`); setItems((current) => current.filter((item) => item._id !== id)); };
  return <div className="min-h-[calc(100vh-4rem)] bg-[#0b1220] p-6 text-white"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">{title}</h1><p className="mt-2 text-slate-400">{subtitle}</p></div><button onClick={() => setOpen(!open)} className="inline-flex items-center gap-2 rounded-xl bg-blue-500 px-4 py-2.5 text-sm font-semibold"><Plus size={17} />New {title.slice(0, -1)}</button></div>{open && <form onSubmit={create} className="mt-6 grid gap-3 rounded-2xl border border-slate-800 bg-slate-900 p-5 sm:grid-cols-2">{fields.map((field) => <label key={field.name} className="text-sm text-slate-300">{field.label}<input name={field.name} required={field.required} className="mt-1.5 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2.5 text-white" /></label>)}<button className="w-fit rounded-lg bg-blue-500 px-4 py-2.5 text-sm font-semibold">Create</button></form>}{error && <p className="mt-5 rounded-xl bg-rose-500/10 p-4 text-sm text-rose-300">{error}</p>}<div className="mt-6 grid gap-3">{loading ? <p className="text-slate-400">Loading…</p> : items.length ? items.map((item) => <article key={item._id} className="flex items-center justify-between rounded-xl border border-slate-800 bg-slate-900 p-4"><div><h2 className="font-medium">{item.name || item.title}</h2><p className="mt-1 text-sm capitalize text-slate-400">{item.status?.replaceAll("_", " ")} · {item.priority || "standard"}</p></div><button onClick={() => remove(item._id)} className="rounded-lg p-2 text-slate-500 hover:bg-rose-500/10 hover:text-rose-300"><Trash2 size={17} /></button></article>) : <div className="rounded-xl border border-dashed border-slate-700 bg-slate-900/50 p-8 text-center text-slate-400">No {title.toLowerCase()} yet. Create your first one to get started.</div>}</div></div>;
}
